.PHONY: clean All

All:
	@echo "==========Building project:[ chapter_1 - Debug ]----------"
	@cd "chapter_1" && "$(MAKE)" -f  "chapter_1.mk"
clean:
	@echo "==========Cleaning project:[ chapter_1 - Debug ]----------"
	@cd "chapter_1" && "$(MAKE)" -f  "chapter_1.mk" clean
