.PHONY: clean All

All:
	@echo "==========Building project:[ chapter_1_test - Debug ]----------"
	@cd "chapter_1" && "$(MAKE)" -f  "chapter_1_test.mk"
clean:
	@echo "==========Cleaning project:[ chapter_1_test - Debug ]----------"
	@cd "chapter_1" && "$(MAKE)" -f  "chapter_1_test.mk" clean
