.PHONY: clean All

All:
	@echo "==========Building project:[ get_char - Debug ]=========="
	@cd "get_char" && "$(MAKE)" -f  "get_char.mk"
clean:
	@echo "==========Cleaning project:[ get_char - Debug ]----------"
	@cd "get_char" && "$(MAKE)" -f  "get_char.mk" clean
